version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: iot_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: americ1234
      MYSQL_DATABASE: aep_portal
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Go IoT Application
  iot-app:
    build: .
    container_name: iot_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=americ1234
      - DB_NAME=aep_portal
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - iot_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  iot_network:
    driver: bridge 